@authApiUrl = http://127.0.0.1:3000/api/auth
@user_token =

## Authentication

### POST login
POST {{authApiUrl}}/login
Content-Type: application/json

{
    "username": "johndoe15",
    "password": "password1"
}

### GET me: authenticated user
GET {{authApiUrl}}/me
Authorization: Bearer {{user_token}}
