# URL references
@baseUrl = http://127.0.0.1:3000
@apiUrl = http://127.0.0.1:3000/api

## login

### POST mock login
POST {{apiUrl}}/login
Content-Type: application/json

{
    "username": "johndoe5",
    "password": "password5"
}
