@baseUrl = http://127.0.0.1:3000
@apiUrl = http://127.0.0.1:3000/api
@usersApiUrl = http://127.0.0.1:3000/api/users
@user_token =

### Olemattoman resurssin testi
GET {{baseUrl}}/343phsgdbg0324

## users

### GET all users
GET {{usersApiUrl}}/
Authorization: Bearer {{user_token}}
### GET all users
GET {{usersApiUrl}}


### GET user by id
GET {{usersApiUrl}}/12
Authorization: Bearer {{user_token}}

### POST add new user
POST {{usersApiUrl}}/
Content-Type: application/json

{
    "username": "johndoe15121",
    "password": "password15121",
    "email": "johndoe202321@example.com",
    "last_name": "Döe"
}

### PUT update an user by id
PUT {{usersApiUrl}}/12
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "email": "newemail-JWT-johndoe1555@example.com",
    "last_name": "Doe5123"
}

### PUT update user's password
PUT {{usersApiUrl}}/5
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "password": "hashedpassword5"
}

### DELETE user by id
DELETE {{usersApiUrl}}/11
Authorization: Bearer {{user_token}}
