@baseUrl = http://127.0.0.1:3000
@apiUrl = http://127.0.0.1:3000/api
@usersApiUrl = http://127.0.0.1:3000/api/users
@user_token =
## users

### GET all users
GET {{usersApiUrl}}/
Authorization: Bearer {{user_token}}
### GET all users
GET {{usersApiUrl}}


### GET user by id
GET {{usersApiUrl}}/12
Authorization: Bearer {{user_token}}

### POST add new user
POST {{usersApiUrl}}/
Content-Type: application/json

{
    "username": "johndoe15",
    "password": "password",
    "email": "johndoe2023@example.com"
}

### PUT update an user by id
PUT {{usersApiUrl}}/12
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "email": "newemail-JWT-johndoe155@example.com",
    "last_name": "Doe12"
}

### PUT update user's password
PUT {{usersApiUrl}}/5
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "password": "hashedpassword5"
}

### DELETE user by id
DELETE {{usersApiUrl}}/11
Authorization: Bearer {{user_token}}
