@authApiUrl = http://127.0.0.1:3000/api/auth
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwidXNlcm5hbWUiOiJqb2huZG9lMTUiLCJlbWFpbCI6ImpvaG5kb2UyMDIzQGV4YW1wbGUuY29tIiwibGFzdF9uYW1lIjpudWxsLCJmaXJzdF9uYW1lIjpudWxsLCJ1c2VyX2xldmVsIjoidXNlciIsImlhdCI6MTc0MTcxMzczNiwiZXhwIjoxNzQxODAwMTM2fQ.jqIIPBeq03jD7Mm3k9TJCzJJp9UFHyP_5PN_hlU5iy8


## Authentication

### POST login
POST {{authApiUrl}}/login
Content-Type: application/json

{
    "username": "johndoe15",
    "password": "password1"
}

### GET me: authenticated user
GET {{authApiUrl}}/me
Authorization: Bearer {{user_token}}
