@symptomsApiUrl = http://127.0.0.1:3000/api/entries/symptoms
@user_token =

## symptom entries

### GET all entries
GET {{symptomsApiUrl}}/all
Authorization: Bearer {{user_token}}

### GET all entries of a user
GET {{symptomsApiUrl}}/
Authorization: Bearer {{user_token}}

### GET entry by id
GET {{symptomsApiUrl}}/16
Authorization: Bearer {{user_token}}
### POST add new entry
POST {{symptomsApiUrl}}/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "entry_date": "2025-03-01",
  "illness_name": "headache",
  "symptom_description": "head hurts",
  "symptom_intensity": "a lot"
}

### PUT update an entry by id
PUT {{symptomsApiUrl}}/1
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "entry_date": "2025-03-02",
  "illness_name": "headache",
  "symptom_description": "updated head hurts",
  "symptom_intensity": "a lot"
}

### DELETE entry by id
DELETE {{symptomsApiUrl}}/27
Authorization: Bearer {{user_token}}
