@diariesApiUrl = http://127.0.0.1:3000/api/entries/diaries
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwidXNlcm5hbWUiOiJqb2huZG9lMTUiLCJlbWFpbCI6ImpvaG5kb2UyMDIzQGV4YW1wbGUuY29tIiwibGFzdF9uYW1lIjpudWxsLCJmaXJzdF9uYW1lIjpudWxsLCJ1c2VyX2xldmVsIjoidXNlciIsImlhdCI6MTc0MTcxMzczNiwiZXhwIjoxNzQxODAwMTM2fQ.jqIIPBeq03jD7Mm3k9TJCzJJp9UFHyP_5PN_hlU5iy8

## diaries

### GET all diaries
GET {{diariesApiUrl}}/
Authorization: Bearer {{user_token}}
### GET all diaries
GET {{diariesApiUrl}}

### GET entry by id
GET {{diariesApiUrl}}/12
Authorization: Bearer {{user_token}}

### POST add new entry
POST {{diariesApiUrl}}/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "user_id": "1",
    "entry_date": "2025-03-09",
    "mood": "good",
    "weight": "75",
    "sleep_hours": "7",
    "notes": "nothing to add"
}

### PUT update an entry by id
PUT {{diariesApiUrl}}/15
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_dat": "2025-03-01",
    "entry_date": "2025-03-02",
    "mood": "good",
    "weight": "75",
    "sleep_hours": "7",
    "notes": "updated entry"
}

### DELETE entry by id
DELETE {{diariesApiUrl}}/10
Authorization: Bearer {{user_token}}

