@drugsApiUrl = http://127.0.0.1:3000/api/entries/drugs
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwidXNlcm5hbWUiOiJqb2huZG9lMTUiLCJlbWFpbCI6ImpvaG5kb2UyMDIzQGV4YW1wbGUuY29tIiwibGFzdF9uYW1lIjpudWxsLCJmaXJzdF9uYW1lIjpudWxsLCJ1c2VyX2xldmVsIjoidXNlciIsImlhdCI6MTc0MTcxMzczNiwiZXhwIjoxNzQxODAwMTM2fQ.jqIIPBeq03jD7Mm3k9TJCzJJp9UFHyP_5PN_hlU5iy8

## drug entries

### GET all drug entries
GET {{drugsApiUrl}}/
Authorization: Bearer {{user_token}}
### GET all drug entries
GET {{drugsApiUrl}}

### GET entry by id
GET {{drugsApiUrl}}/1
Authorization: Bearer {{user_token}}

### POST add new entry
POST {{drugsApiUrl}}/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_date": "2025-03-01",
    "drug_name": "Burana",
    "drug_strength_amount": "600",
    "drug_strength_unit": "mg",
    "drug_amount": "2"
}

### PUT update an entry by id
PUT {{drugsApiUrl}}/27
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_date": "2025-03-01",
    "drug_name": "updated2Burana",
    "drug_strength_amount": "600",
    "drug_strength_unit": "mg",
    "drug_amount": "2"
}

### DELETE entry by id
DELETE {{drugsApiUrl}}/1
Authorization: Bearer {{user_token}}

