@drugsApiUrl = http://127.0.0.1:3000/api/entries/drugs
@user_token =

## drug entries

### GET all entries
GET {{drugsApiUrl}}/all
Authorization: Bearer {{user_token}}
### GET all entries
GET {{drugsApiUrl}}/all

### GET all entries of a user
GET {{drugsApiUrl}}/
Authorization: Bearer {{user_token}}

### GET entry by id
GET {{drugsApiUrl}}/32
Authorization: Bearer {{user_token}}

### POST add new entry
POST {{drugsApiUrl}}/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_date": "2025-03-01",
    "drug_name": "Burana",
    "drug_strength_amount": "600",
    "drug_strength_unit": "mg",
    "drug_amount": "2"
}

### PUT update an entry by id
PUT {{drugsApiUrl}}/32
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_date": "2025-03-01",
    "drug_name": "updated2Burana",
    "drug_strength_amount": "600",
    "drug_strength_unit": "mg",
    "drug_amount": "2"
}

### DELETE entry by id
DELETE {{drugsApiUrl}}/32
Authorization: Bearer {{user_token}}

