@diariesApiUrl = http://127.0.0.1:3000/api/entries/diaries
@user_token =

## diaries

### GET all entries
GET {{diariesApiUrl}}/all
Authorization: Bearer {{user_token}}
### GET all entries
GET {{diariesApiUrl}}/all

### GET all entries of a user
GET {{diariesApiUrl}}/
Authorization: Bearer {{user_token}}

### GET entry by id
GET {{diariesApiUrl}}/32
Authorization: Bearer {{user_token}}

### POST add new entry
POST {{diariesApiUrl}}/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_date": "2025-03-09",
    "mood": "good",
    "weight": "75",
    "sleep_hours": "7",
    "notes": "nothing to add"
}

### PUT update an entry by id
PUT {{diariesApiUrl}}/32
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "entry_dat": "2025-03-01",
    "entry_date": "2025-03-02",
    "mood": "good",
    "weight": "10.31",
    "sleep_hours": "7",
    "notes": "updated entry"
}

### DELETE entry by id
DELETE {{diariesApiUrl}}/15
Authorization: Bearer {{user_token}}

